services:
  gitea:
    image: gitea/gitea@sha256:a9dc25679ebdd33356242d2e0667cc220043745e8339922879f187c20329a42e
    restart: always
    networks:
      - cftunnel
    volumes:
      - /mnt/hd1/gitea/:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  tunnel:
    image: cloudflare/cloudflared@sha256:9b49eed8f62806d5d45ddf59ecefb5710429598ea6d3fcccd2af938f621b2b07
    restart: always
    networks:
      - cftunnel
    command: tunnel run --token ${TUNNEL_TOKEN}
networks:
  cftunnel:
    enable_ipv6: true
