services:
  gitea:
    image: gitea/gitea@sha256:d20286ca2b2e170fdf628e7231b8a31a3220ade39ff462b55041d43d1fc757dd
    restart: always
    networks:
      - cftunnel
    volumes:
      - /mnt/hd1/gitea/:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  tunnel:
    image: cloudflare/cloudflared@sha256:0aa26e284f05e6c77ae375b8c9c11d9eb6a448fb7bcd8d40f31cb6176189eb38
    restart: always
    networks:
      - cftunnel
    command: tunnel run --token ${TUNNEL_TOKEN}
networks:
  cftunnel:
    enable_ipv6: true
