services:
  gitea:
    image: gitea/gitea@sha256:137a322f0308056415bc1a14a4ca8607b2e8efcb8154dfc5049b1f7f8b0a9b71
    restart: always
    networks:
      - cftunnel
    volumes:
      - /mnt/hd1/gitea/:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  tunnel:
    image: cloudflare/cloudflared@sha256:175aee7e8b548f983f7e3b79ace217676d2a79255a73c074dacb491e59603679
    restart: always
    networks:
      - cftunnel
    command: tunnel run --token ${TUNNEL_TOKEN}
networks:
  cftunnel:
