services:
  gitea:
    image: gitea/gitea@sha256:34e3f6b75f5cbb6aebce588037fc5a53c84213e4d4b00da0a8d73e031a558e52
    restart: always
    networks:
      - cftunnel
    volumes:
      - /mnt/hd1/gitea/:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  tunnel:
    image: cloudflare/cloudflared@sha256:12ff5c6992a9863db4da270746af7c244bcaee49353039af8104268a18d6c4f0
    restart: always
    networks:
      - cftunnel
    command: tunnel run --token ${TUNNEL_TOKEN}
networks:
  cftunnel:
    enable_ipv6: true
